---

base_locale: en
locales: [en]

ignore_unused:
  - decidim.components.elections.name"
  - decidim.elections.trustee_zone.menu.trustee_zone

ignore_missing:
  - decidim.participatory_processes.scopes.global
